# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            farcrycore
tagline:          'farcrycore code committers'
description:      'Fulminations of the FarCry Core code committers.'
url:              http://blog.farcrycore.org
baseurl:          /
excerpt_separator:	'<!--more-->'

author:
  name:           'Daemonites'
  url:            https://twitter.com/farcrycore

paginate:         5

# Custom vars
version:          7.2

github:
  repo:           https://github.com/farcrycore
